name: Node.js CI

on:
  push:
    branches: [ "master", "security" ]
  pull_request:
    branches: [ "master", "security" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Clean up node_modules and lock file before installation
    - name: Clean install
      run: |
        rm -rf node_modules
        rm -f package-lock.json
        rm -f yarn.lock
        yarn 
    
    - name: Checkout repo
      uses: actions/checkout@v2
  
    - name: Run Prisma Cloud 
      id: prisma-cloud
      uses: bridgecrewio/checkov-action@master
      env:
        PRISMA_API_URL: https://api2.prismacloud.io
      with:
        api-key: ${{ secrets.BC_API_KEY }}
    
